version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: ["serve", "-s", "public", "-l", "3000"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  gerador:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "gerador.py"]
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    build:
      context: ./Mysql
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: walker1207
      MYSQL_DATABASE: app_db
      MYSQL_USER: dbpi
      MYSQL_PASSWORD: walker1207
    volumes:
      - db_data:/var/lib/mysql

  rscript:
    build:
      context: .
      dockerfile: rscript/Dockerfile
    # volumes:
    #   - .:/app  # Comente se não quiser sobrepor os arquivos copiados no build
    
volumes:
  db_data:
