FROM r-base

WORKDIR /app

# Instala dependências para rmarkdown e pandoc
RUN apt-get update && apt-get install -y \
    pandoc \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev

# Copia o arquivo .Rmd para o container
COPY teste.Rmd /app/teste.Rmd
COPY escolas_selecionadas.CSV /app/escolas_selecionadas.CSV


# Instala o pacote rmarkdown
RUN R -e "install.packages('rmarkdown', repos='http://cran.rstudio.com')"

# Comando para renderizar
CMD ["R", "-e", "rmarkdown::render('teste.Rmd')"]
