disciplinas_por_curso = {
    'Administração': ['Administração Geral', 'Gestão de Pessoas', 'Gestão Financeira', 'Marketing', 'Economia'],
    'Direito': ['Direito Civil', 'Direito Penal', 'Processo Civil', 'Processo Penal', 'Constitucional'],
    'Engenharia': ['Cálculo', 'Física Aplicada', 'Mecânica', 'Circuitos Elétricos', 'Desenho Técnico'],
    'Pedagogia': ['Psicopedagogia', 'Teoria da Educação', 'Didática', 'Educação Infantil', 'Gestão Escolar'],
    'Psicologia': ['Psicologia Geral', 'Teorias da Personalidade', 'Psicopatologia', 'Psicologia do Desenvolvimento', 'Psicologia Social'],
    'Engenharia Civil': ['Construção Civil', 'Cálculo Estrutural', 'Mecânica dos Solos', 'Topografia', 'Materiais de Construção'],
    'Engenharia Elétrica': ['Circuitos Elétricos', 'Eletrônica', 'Sistemas Elétricos', 'Máquinas Elétricas', 'Transformadores'],
    'Engenharia Mecânica': ['Mecânica dos Fluidos', 'Termodinâmica', 'Resistência dos Materiais', 'Desenho Técnico', 'Sistemas Mecânicos'],
    'Engenharia de Produção': ['Gestão de Processos', 'Gestão da Qualidade', 'Planejamento de Produção', 'Logística', 'Gestão de Estoques'],
    'Arquitetura e Urbanismo': ['Desenho Arquitetônico', 'Planejamento Urbano', 'História da Arquitetura', 'Construção Civil', 'Estruturas'],    'Medicina': ['Anatomia', 'Fisiologia', 'Patologia', 'Farmacologia', 'Clínica Médica'],
    'Enfermagem': ['Enfermagem Geral', 'Cuidado Intensivo', 'Anatomia e Fisiologia', 'Saúde Pública', 'Psicologia da Saúde'],
    'Biomedicina': ['Genética', 'Imunologia', 'Microbiologia', 'Biologia Molecular', 'Farmacologia'],
    'Educação Física': ['Fisiologia do Exercício', 'Cinesiologia', 'Psicologia do Esporte', 'Nutrição Esportiva', 'Gestão do Esporte'],
    'Fisioterapia': ['Terapia Física', 'Fisiologia', 'Reabilitação', 'Técnicas de Imagem', 'Anatomia'],
    'Odontologia': ['Anatomia Dental', 'Periodontia', 'Implantes', 'Radiologia Odontológica', 'Clínica Odontológica'],
    'Farmácia': ['Química Farmacêutica', 'Farmacologia', 'Análises Clínicas', 'Microbiologia', 'Cosmetologia'],
    'Veterinária': ['Anatomia Veterinária', 'Clínica Veterinária', 'Microbiologia Veterinária', 'Farmacologia Veterinária', 'Cirurgia Veterinária'],
    'Nutrição': ['Nutrição Clínica', 'Nutrição Esportiva', 'Técnicas de Cozinha', 'Nutrição Infantil', 'Psicologia da Alimentação'],
    'Computação': ['Algoritmos', 'Estruturas de Dados', 'Banco de Dados', 'Sistemas Operacionais', 'Programação'],    'Ciência da Computação': ['Estruturas de Dados', 'Algoritmos', 'Inteligência Artificial', 'Redes de Computadores', 'Sistemas Distribuídos'],
    'Sistemas de Informação': ['Banco de Dados', 'Análise de Sistemas', 'Gestão de Projetos de TI', 'Sistemas de Informação Empresarial', 'Desenvolvimento de Software'],
    'Análise e Desenvolvimento de Sistemas': ['Programação', 'Banco de Dados', 'Sistemas Operacionais', 'Engenharia de Software', 'Segurança da Informação'],
    'Jogos Digitais': ['Design de Jogos', 'Programação de Jogos', 'Gráficos de Computação', 'Realidade Virtual', 'Inteligência Artificial para Jogos'],
    'Redes de Computadores': ['Redes de Dados', 'Protocolos de Comunicação', 'Segurança em Redes', 'Administração de Redes', 'Arquitetura de Redes'],
    'Banco de Dados': ['Modelagem de Dados', 'SQL Avançado', 'Administração de Banco de Dados', 'Sistemas de Informação', 'Segurança de Banco de Dados'],
    'Matemática': ['Cálculo', 'Geometria', 'Álgebra Linear', 'Probabilidade e Estatística', 'Teoria dos Números'],
    'Física': ['Mecânica', 'Eletromagnetismo', 'Termodinâmica', 'Óptica', 'Física Nuclear'],
    'Química': ['Química Orgânica', 'Química Inorgânica', 'Físico-Química', 'Bioquímica', 'Química Analítica'],
    'Biologia': ['Biologia Celular', 'Genética', 'Ecologia', 'Botânica', 'Zoologia'],
    'Geografia': ['Geografia Física', 'Geopolítica', 'Cartografia', 'Geografia Humana', 'Planejamento Urbano'],    'História': ['História Geral', 'História do Brasil', 'História Contemporânea', 'Teoria Histórica', 'Historiografia'],
    'Letras': ['Literatura Brasileira', 'Literatura Portuguesa', 'Gramática', 'Linguística', 'Produção Textual'],
    'Serviço Social': ['Política Social', 'Direitos Humanos', 'Ética no Serviço Social', 'Gestão Social', 'Cultura e Sociedade'],
    'Relações Internacionais': ['Teoria das Relações Internacionais', 'Política Internacional', 'Direitos Humanos', 'Economia Internacional', 'Geopolítica'],
    'Jornalismo': ['Redação Jornalística', 'Ética Jornalística', 'Edição de Vídeo', 'Produção de Conteúdo', 'Comunicação e Mídia'],
    'Publicidade e Propaganda': ['Comunicação Publicitária', 'Marketing Digital', 'Publicidade Criativa', 'Comportamento do Consumidor', 'Relações Públicas'],
    'Design Gráfico': ['Teoria do Design', 'Design Digital', 'Tipografia', 'Design Editorial', 'Design de Interfaces'],
    'Marketing': ['Comportamento do Consumidor', 'Gestão de Marketing', 'Pesquisa de Mercado', 'Publicidade', 'Marketing Digital'],
    'Recursos Humanos': ['Gestão de Pessoas', 'Desenvolvimento Organizacional', 'Recrutamento e Seleção', 'Treinamento e Desenvolvimento', 'Gestão de Carreira'],
    'Engenharia Ambiental': ['Gestão Ambiental', 'Tecnologias Ambientais', 'Ecologia', 'Política Ambiental', 'Sistemas de Gestão Ambiental'],    'Engenharia de Alimentos': ['Tecnologia de Alimentos', 'Química de Alimentos', 'Microbiologia de Alimentos', 'Higiene e Sanidade', 'Gestão de Processos'],
    'Engenharia Química': ['Processos Químicos', 'Termodinâmica', 'Cinética Química', 'Reatores Químicos', 'Química Industrial'],
    'Zootecnia': ['Nutrição Animal', 'Genética Animal', 'Fisiologia Animal', 'Medicina Veterinária', 'Produção Animal'],
    'Gastronomia': ['Culinária Internacional', 'Gestão de Restaurante', 'Nutrição e Dietética', 'Cultura Gastronômica', 'Técnicas Culinárias'],
    'Moda': ['Design de Moda', 'História da Moda', 'Gestão de Moda', 'Marketing da Moda', 'Produção de Moda'],
    'Teatro': ['Direção Teatral', 'Roteiro Teatral', 'Cenografia', 'Iluminação Teatral', 'História do Teatro'],
    'Música': ['Teoria Musical', 'História da Música', 'Prática Instrumental', 'Composição Musical', 'Arranjo Musical'],
    'Dança': ['História da Dança', 'Técnicas de Dança', 'Coreografia', 'Gestão de Eventos de Dança', 'Dança Contemporânea'],
    'Cinema': ['Roteiro de Cinema', 'Direção de Cinema', 'Produção de Cinema', 'Montagem de Cinema', 'História do Cinema'],
    'Artes Visuais': ['Pintura', 'Escultura', 'Arte Digital', 'Fotografia', 'História da Arte'],    'Ciências Contábeis': ['Contabilidade Geral', 'Contabilidade de Custos', 'Contabilidade Tributária', 'Auditoria', 'Análise Financeira'],
    'Ciências Econômicas': ['Microeconomia', 'Macroeconomia', 'Economia Internacional', 'Teoria Econômica', 'Política Econômica'],
    'Teologia': ['História da Igreja', 'Teologia Sistemática', 'Exegese Bíblica', 'Teologia Moral', 'Filosofia da Religião'],
    'Fonoaudiologia': ['Fonologia', 'Audiologia', 'Reabilitação Fonoaudiológica', 'Psicologia do Desenvolvimento', 'Anatomia e Fisiologia'],
    'Terapia Ocupacional': ['Técnicas de Reabilitação', 'Fisioterapia', 'Psicologia Clínica', 'Avaliação Terapêutica', 'Desenvolvimento Humano'],
    'Gestão Pública': ['Gestão de Políticas Públicas', 'Administração Pública', 'Finanças Públicas', 'Gestão de Projetos', 'Gestão de Pessoas'],
    'Gestão Comercial': ['Gestão de Vendas', 'Comportamento do Consumidor', 'Marketing e Vendas', 'Gestão de Estoques', 'Gestão de Relacionamento'],
    'Logística': ['Gestão de Transportes', 'Gestão de Estoques', 'Gestão de Cadeia de Suprimentos', 'Transporte e Distribuição', 'Logística Internacional'],
    'Secretariado Executivo': ['Gestão de Escritórios', 'Gestão de Pessoas', 'Comunicação Empresarial', 'Administração do Tempo', 'Atendimento ao Cliente'],
    'Turismo': ['Gestão de Turismo', 'Planejamento de Turismo', 'Marketing Turístico', 'História do Turismo', 'Turismo Cultural'],   'Hotelaria': ['Gestão de Hotelaria', 'Marketing de Hotelaria', 'Gestão de Hospedagem', 'Gestão de Alimentos e Bebidas', 'Hospitalidade'],
    'Ciências Sociais': ['Sociologia Geral', 'Antropologia', 'Teoria Social', 'Movimentos Sociais', 'Psicologia Social'],
    'Estatística': ['Estatística Descritiva', 'Probabilidade', 'Análise de Dados', 'Métodos Estatísticos', 'Estatística Aplicada'],
    'Biblioteconomia': ['Catalogação', 'Gestão de Bibliotecas', 'Preservação de Documentos', 'Leitura e Literatura', 'Gestão da Informação'],
    'Arquivologia': ['Gestão de Arquivos', 'Documentação Digital', 'Teoria Arquivística', 'Preservação de Documentos', 'Arquivos Públicos'],
}

disciplinas_gerais = ['Matemática', 'História', 'Física', 'Química', 'Português', 'Sociologia', 'Biologia', 'Filosofia', 'Economia', 'Geografia']