FROM mysql:8.3

# Define variáveis de ambiente (podem ser sobrescritas no docker run se quiser)
ENV MYSQL_ROOT_PASSWORD=@Walker1207
ENV MYSQL_DATABASE=dockerpi
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=@Walker1207
# Expondo a porta padrão do MySQL
EXPOSE 3306
