
```{r}
alunos = read.csv("alunos_com_erros.csv", sep = ",")
head(alunos)
str(alunos)
summary(alunos)
```

```{r}
colnames(alunos) = c(
  "id", "nome", "email", "curso", "status", "turma", "sexo", "idade", 
  "trabalha", "renda", "acompanhamento_medico", "tem_filho", "estado_civil", 
  "semestre", "bimestre", 
  "aula1", "professor1", "nota1", "falta1", "desempenho1", 
  "aula2", "professor2", "nota2", "falta2", "desempenho2", 
  "aula3", "professor3", "nota3", "falta3", "desempenho3", 
  "aula4", "professor4", "nota4", "falta4", "desempenho4", 
  "aula5", "professor5", "nota5", "falta5", "desempenho5", 
  "risco_evasao"
)
alunos
```

```{r}
#Verificando campos com na
sapply(alunos, function(x) sum(x == "", na.rm = TRUE))
alunos$curso[alunos$curso == ""] = NA
alunos$nome[alunos$nome == ""] = "Desconhecido"
alunos$email[alunos$email == ""] = "Sem e-mail"
alunos$sexo[alunos$sexo == ""] = "Não informado"
```

```{r}
#Correção dos nomes desconhecidos
head(alunos$nome)
duplicados = alunos$nome[duplicated(alunos$nome)]
unique(duplicados)
nomes_invalidos = c("Desconhecido", "NULL", "#######", "0923023")
nome_do_email = sub("@.*", "", alunos$email)
alunos$nome[alunos$nome %in% nomes_invalidos] = nome_do_email[alunos$nome %in% nomes_invalidos]

```

```{r}
#Analise de Idade outliers
boxplot(alunos$idade, main = "Boxplot da Idade", ylab = "Idade", col = "lightblue")
boxplot.stats(alunos$idade)$out
# Calcular média com valores válidos apenas
media_idade = mean(alunos$idade[alunos$idade >= 10 & alunos$idade <= 100], na.rm = TRUE)
# Substituir idades inválidas pela média
alunos$idade[alunos$idade < 10 | alunos$idade > 100] = round(media_idade)

```

```{r}
#Analise das notas outliers
boxplot(alunos[, c("nota1", "nota2", "nota3", "nota4", "nota5")],
        main = "Boxplot das Notas",
        col = "lightgreen",
        ylab = "Notas")

```


```{r}
#Analise das Renda outliers
boxplot(alunos[, c("renda")],
        main = "Boxplot - Idade e Renda",
        col = c("orange", "pink"),
        outline = TRUE) 

media_renda = mean(alunos$renda[alunos$renda > 0 & alunos$renda < 50000], na.rm = TRUE)
alunos$renda[alunos$renda < 0 | alunos$renda > 50000] = round(media_renda, 2)

```


```{r}
#Analise das Faltas outliers
boxplot(alunos[, c("falta1", "falta2", "falta3", "falta4", "falta5")],
        main = "Boxplot das Faltas",
        col = "lightgreen",
        ylab = "Notas")
alunos
```


```{r}
# Salvar como CSV
write.csv(dados_limpos, "dados_alunos_limpos.csv", row.names = FALSE, fileEncoding = "UTF-8")
```