---
title: "EDA_PI_Do_Mal"
---

Leitura do arquivo xlsx
```{r}
dados = read.csv2("C:/FACULDADE/7_SEMESTRE/PI_DATA_SCIENCE/files/alunos_detalhes.csv", sep=';', na.strings = "", stringsAsFactors = T)
head(dados)
summary(dados)
```
Limpeza e conferencia de dados
```{r}
counts = table(dados$estado)
counts

str(dados)
dados$salario_medio = as.numeric(dados$salario_medio)
dados$nota = as.numeric(dados$nota)
```
Explorando os dados de salario medio
```{r}
summary(dados$salario_medio)
boxplot(dados$salario_medio)
hist(dados$salario_medio)
```
Explorando os dados de uso de alcool pelos alunos
```{r}
summary(dados$uso_alcool)
boxplot(dados$uso_alcool)
hist(dados$uso_alcool)
```
Explorando os dados de tabagismo dos alunos
```{r}
summary(dados$fuma)
boxplot(dados$fuma)
hist(dados$fuma)
```


Explorando os dados de uso de drogas pelos alunos
```{r}
summary(dados$uso_drogas)
boxplot(dados$uso_drogas)
hist(dados$uso_drogas)
```
Explorando as notas dos alunos
```{r}
summary(dados$nota)
boxplot(dados$nota)
hist(dados$nota)
```

